name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        NUGET_KEY: ${{ secrets.PWSHGALLERY }}
      shell: pwsh
      run: |
        (Get-Location).Path
        Write-host $env:GITHUB_WORKSPACE
        Write-Host $env:GITHUB_RUN_NUMBER
