name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        PWSHGALLERY: ${{ secrets.PWSHGALLERY }}
      shell: pwsh
      run: |
        .\build_scripts\build.ps1
