name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        NUGET_KEY: ${{ secrets.PWSHGALLERY }}
      shell: pwsh
      run: |
        Get-Location
        Write-host $GITHUB_WORKSPACE
        Write-Host $GITHUB_RUN_NUMBER
